@apiurl = http://localhost:4000
# @apiurl = https://gorest.co.in/public-api

### GET users
GET {{apiurl}}/products HTTP/1.1

### POST products
POST {{apiurl}}/product HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name":"Notebook",
   "bar_code": "Nh68hyhhs",
   "price": 5000
 }


### POST categories
POST http://localhost:4000/category
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name":"informatic"
}


### POST productCategory
POST {{apiurl}}/productCategory HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "id_product":"483fd210-314d-4f9e-b7b6-20d55de7d5b3",
   "id_category": "608482bc-3cd1-41ba-aeff-2f18e02bc025"
}
### POST productWithCategoryExists
POST http://localhost:4000/productWithCategoryExist
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name":"Smartphone",
   "bar_code": "233fgggggg",
   "price": 3500,
   "id_category": "ea0fee85-4f82-473d-847b-e553f0038d19"
 }
### GET categories
GET {{apiurl}}/categories HTTP/1.1

### GET findProducts
GET http://localhost:4000/findProducts


# -----------------

# @apiurl = https://gorest.co.in/public-api

# ### GET users
# GET {{apiurl}}/users HTTP/1.1

# ### POST users
# POST {{apiurl}}/users HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer ACCESS-TOKEN

# {
#    "name":"Tenali Ramakrishna",
#    "gender":"Male",
#    "email":"tenali.ramakrishna@15ce.com",
#    "status":"Active"
# }

# ### GET categories
# GET {{apiurl}}/categories HTTP/1.1