# users

### GET find users
GET http://localhost:4000/users

### GET users by email
GET http://localhost:4000/user/futa@gmail.com

### POST create user
POST http://localhost:4000/user
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name":"Miguel Futa",
   "email": "futan@gmail.com",
   "password": "1234",
   "admin": true
   
 }

### POST find user by email
POST http://localhost:4000/user/email
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "email": "victoriano@gmail.com"
 }

### POST find user by id
POST http://localhost:4000/user/id
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "id": "a820ad01-c312-499e-947e-1eb8bbfb5418"
 }


### POST authenticate user < /login  >
POST http://localhost:4000/login
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "email": "ismaelmuanza@gmail.com",
    "password": "0000"
 }


#  tags
### POST tag
POST http://localhost:4000/tag
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name": "kind"
 }

### POST find tag by name
POST http://localhost:4000/tag/name
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name": "fantastic"
 }


### POST create complit 
POST http://localhost:4000/compliment
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "id_user_sender": "fantastic",
   "id_user_receiverr": "fantastic",
   "id_tag": "fantastic",
   "message": "fantastic"
 }
