# users

### GET find users
GET http://localhost:4000/users

### GET users by email
GET http://localhost:4000/user/futa@gmail.com

### POST create user
POST http://localhost:4000/user
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name":"Ismael Muanza",
   "email": "ismaelmuanza@gmail.com",
   "password": "1234",
   "admin": true
   
 }

### POST find user by email
POST http://localhost:4000/user/email
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "email": "victoriano@gmail.com"
 }

### POST find user by id
POST http://localhost:4000/user/id
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "id": "a820ad01-c312-499e-947e-1eb8bbfb5418"
 }


### POST authenticate user < /login  >
POST http://localhost:4000/login
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "email": "victoriano@gmail.com",
    "password": "1234"
 }

# tags

### POST create tag
POST http://localhost:4000/tag
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpY3Rvcmlhbm9AZ21haWwuY29tIiwiYWRtaW4iOmZhbHNlLCJpYXQiOjE3NDA0OTQzNzQsImV4cCI6MTc0MDU4MDc3NCwic3ViIjoiYTcyYWUyOTEtOTA5My00MjdmLWI3NWQtMmNmMWNiYmE0MmVjIn0.v1rXi-CuOidqCgtEwKj9ccbiX1C8Xa4Oj5qN6AENPhg

{
   "name": "kind"
 }

### POST find tag by name
POST http://localhost:4000/tag/name
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
   "name": "fantastic"
 }


### POST create complit 
POST http://localhost:4000/compliment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpY3Rvcmlhbm9AZ21haWwuY29tIiwiaWF0IjoxNzQwNDk1Nzk5LCJleHAiOjE3NDA1ODIxOTksInN1YiI6ImE3MmFlMjkxLTkwOTMtNDI3Zi1iNzVkLTJjZjFjYmJhNDJlYyJ9.B2Y1hOZC4dkD9gHpdwmTpoob5f2JZjh5Elp2rbLGptg

{
   "id_user_receiver": "2c954ec5-52ae-4916-a37d-5444f0cee86d",
   "id_tag": "7fab0628-f3a4-444d-b51f-50e06813d14f",
   "message": "You are incredible, I want be like you when I grown up"
 }
